name: mlgeo_sk
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - pyarrow
  - plotly
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - rasterio
  - scikit-learn
  - shapely
  - netcdf4
  - wget
  - h5py
  - zarr
  - xarray
  - folium
  - nbgitpuller
  - pip=20
